# Generated by Django 3.2.6 on 2021-09-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_messagemodel_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='user',
        ),
        migrations.DeleteModel(
            name='MessageModel',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
