# Generated by Django 3.2 on 2021-07-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='not_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
