# Generated by Django 3.2 on 2021-07-23 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_messagemodel_thread'),
        ('notifications', '0002_alter_notification_not_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.thread'),
        ),
    ]
